spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/blabla_demo?createDatabaseIfNotExist=true&useSSL=true&requireSSL=false&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&interactive_timeout=6&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC

blabladem:
  exception:
    #whether to show extended exception information in case of error or not
    returnExtendedInfo: true